### ISSUE TITLE
Good to monitor the resources of containers

### ISSUE THREAD

**Issue by tobegit3hub** [tobegit3hub/seagull#13]
Someone want this from seagull. Actually cAdvisor has monitored resources of containers by using cgroups directly. I hope the docker remote API could support this so that we don't have to access another files and do the repeated jobs.

Now it's blocked by <https://github.com/docker/docker/issues/8842>.

Feel free to push us about this :smiley_cat:

**Comment by tobegit3hub** [comment]
We can test it by adding the source `add-apt-repository ppa:docker-maint/testing` to install docker 1.7-dev.

**Comment by tobegit3hub** [comment]
Notice that it only works for 1.7+ Docker Remote API.

**Comment by mahesh3267** [comment]
Hi All, 

Myself using docker 1.7 , still not getting any values under Processes & Resources for running containers. 
Kindly Suggest.
![capture](https://cloud.githubusercontent.com/assets/4743043/8376029/95b68c7a-1bfa-11e5-8c4a-7b083700a398.JPG)

**Comment by tobegit3hub** [comment]
Hi @mahesh3267 

You can access `/dockerapi/containers/:id/stats` to test if the api response json data for you. Or just click the json button above and change to this api. It may be the problem of the version of docker daemon.
