### ISSUE TITLE
translation guideline

### ISSUE THREAD

**Issue by larrycai** [tobegit3hub/seagull#31]
will be nice to have translation guideline under development category or other place, so it can be shown to volunteers to get support.

It could get easy help for people has less knowledge of seagull.

larry

**Comment by tobegit3hub** [comment]
Please refer to https://github.com/tobegit3hub/seagull/blob/master/docs/en/development/seagull-translate-guide.md

And in Chinese https://github.com/tobegit3hub/seagull/blob/master/docs/zh/development/seagull-translate-guide.md
