### ISSUE TITLE
ping issue firewall 

### ISSUE THREAD

**Issue by nikola-simple-task** [tobegit3hub/seagull#34]
You forgot that some some server got icpm disabled. Ping will not work.
So only way to fix that is to disable ping in:
<pre>
$scope.addServer = function (newServer) {

    /* Check if we can access the new server */
    //$http.get(canonicalizeServer(newServer) + '/_ping').success(function(data) {
      //if (data === "OK") {
        alert_success("Add server " + newServer);

        $scope.servers.push(newServer)
        $scope.currentServer = newServer;
        $rootScope.canonicalServer = canonicalizeServer($scope.currentServer);
        $scope.notCurrentServers = unique($scope.servers.slice(0).remove($scope.currentServer)); // D
eep copy

        $route.reload();
      //}
    //}).error(function(data){alert_error('Can\'t add this server')});

  };</pre>

**Comment by tobegit3hub** [comment]
Wow. Thanks @nikola-simple-task and I have not considered about this.

It's the trade-off because I add it for https://github.com/tobegit3hub/seagull/issues/22. And adding the wrong remote server is annoying.

Maybe we should not `ping` the server but send the real request to test if the server works.

**Comment by tobegit3hub** [comment]
We should make sure that `/_ping` is using ICMP just like command `ping`. Have you tested in your environment? @nikola-simple-task

**Comment by tobegit3hub** [comment]
Then endpoint `_ping` is the service from docker daemon. It should work no matter we disable icmp or not. I'm gonna close this and feel free to re-open it if we have more problem about this :smile:
