### ISSUE TITLE
Not really an issue, but could we have no-wrap option for container columns? 

### ISSUE THREAD

**Issue by ZenGirl** [tobegit3hub/seagull#39]
Basically I am using your great tool to monitor some 40+ containers on multiple servers.
Unfortunately some of the names and images are quite long.
Similar to this (not quite real) example: "api-internal-party_contact_mechanism_purposes"
The display wraps this, the image name, the ports and the status in the table on the dashes, making it a tad difficult to read quickly.
It's not really an issue but it would be nice to have the ability for the table to expand with no wraps on those columns.
Perhaps a tick box just before the filter drop down?

**Comment by tobegit3hub** [comment]
It may be the problem of Bootstrap table. I will try by myself and figure out the best way to fix it :smiley:

**Comment by tobegit3hub** [comment]
And thanks for your reporting @ZenGirl

**Comment by tobegit3hub** [comment]
Bootstrap works like what we expect. Your advice is reasonable as well.

![seagull-with-long-name](https://cloud.githubusercontent.com/assets/2715000/6801059/a4ab42aa-d25f-11e4-87db-e7c2b3e9dffb.png)

**Comment by tobegit3hub** [comment]
We have tried `nowrap` but it seems not a good idea. Here's the screenshot.

![seagull-with-long-name](https://cloud.githubusercontent.com/assets/2715000/6802793/2ad1f9e2-d26e-11e4-9271-fa2677f32483.png)

**Comment by tobegit3hub** [comment]
Well, now we're making it much prittier. And hope you like it. Close by https://github.com/tobegit3hub/seagull/commit/2055e00ac782222f89faa6a94e0a14b8a8aa890d

![image](https://cloud.githubusercontent.com/assets/2715000/6803053/0b9dd1c0-d270-11e4-9a54-635b1d759b9f.png)

**Comment by YingyiDai** [comment]
Good job!
