### ISSUE TITLE
reduce the image size with Alpine Linux

### ISSUE THREAD

**Issue by SydOps** [tobegit3hub/seagull#56]
@tobegit3hub 

I change Dockerfile with Alpine Linux, and update in my fork. New image is only 171MB.

    $ docker images |grep seagull
    sydops/seagull                  latest      d24ca67818e9        37 seconds ago       171.6 MB
    tobegit3hub/seagull             latest      38bfd833ae80        6 weeks ago          548.5 MB

Updated Dockerfile is here:

https://github.com/BWITS/seagull/blob/master/Dockerfile

If you are fine with this change, I will raise pull request, otherwise, keep it in my fork.

**Comment by larrycai** [comment]
could be good choice, or we can have different tag for this, like

     tobegit3hub/seagull:alpine
tobegit3hub/seagull:dev



On Tue, Aug 11, 2015 at 10:11 PM, Bill W <notifications@github.com> wrote:

> @tobegit3hub <https://github.com/tobegit3hub>
>
> I change Dockerfile with Alpine Linux, and update in my fork. New image is
> only 171MB.
>
> $ docker images |grep seagull
> sydops/seagull                  latest      d24ca67818e9        37 seconds ago       171.6 MB
> tobegit3hub/seagull             latest      38bfd833ae80        6 weeks ago          548.5 MB
>
> Update Dockerfile is here:
>
> https://github.com/SydOps/seagull/blob/master/Dockerfile
>
> If you are fine with this change, I will raise pull request, otherwise,
> keep it in my fork.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tobegit3hub/seagull/issues/56>.
>



-- 
True software development embraces consistent inconsistency.
blog: http://larrycaiyu.com/blog (en), http://larrycaiyu.com (chinese)

**Comment by tobegit3hub** [comment]
Great job @SydOps . It's really nice to make the docker image much smaller.

But I'm not familiar with the `alpine` base image. Please allow me to learn more about this :smiley:

**Comment by SydOps** [comment]
No more updates, then close it. 

I have pushed the image to hub.docker.com from my fork, and works fine in that way.

**Comment by tobegit3hub** [comment]
Thanks @SydOps and sorry for the slow response.

We will checkout your image and try to satisfy most developers' need.

**Comment by SydOps** [comment]
@tobegit3hub 

Now you need think to move the image to alpine. 

http://siliconangle.com/blog/2016/02/09/docker-gets-minimalist-with-plan-to-migrate-images-to-alpine-linux/

If you are happy this this idea, I will raise pull request to update `Dockerfile` with Alpine base image.

**Comment by tobegit3hub** [comment]
Great and I have noticed that news. You're really welcome to contribute the new Dockerfile with Alpine base image :smile:

**Comment by SydOps** [comment]
@tobegit3hub 

I build the docker image with error now, can you take a look?
```
 ---> Running in eb3b8cfd6053
# github.com/tobegit3hub/seagull/controllers
go/src/github.com/tobegit3hub/seagull/controllers/default.go:14: this.TplNames undefined (type *MainController has no field or method TplNames)
```

**Comment by tobegit3hub** [comment]
It seems that `seagull` would not work with the latest `beego`. I'm going to fix that later. Before that we could `git clone` the code instead of `go get` and compile with `godep go build`.

**Comment by dlsniper** [comment]
I have created a version of this which in turn shrinks the image down from ~560mb to about ~20mb, please see #62.

**Comment by SydOps** [comment]
@dlsniper 

Great job. Seems I can retire. 

That's impossible, how you made it. :+1:
