### ISSUE TITLE
centos problem

### ISSUE THREAD

**Issue by qizisheng** [tobegit3hub/seagull#65]
i have dockerUI running ok on Centos7 with docker 1.10.1

once seagull is started successfully, browse the host:10086, the home page dont show
and docker logs -f shows

2016/02/20 08:26:53 [router.go:853][C] the request url is  /
2016/02/20 08:26:53 [router.go:854][C] Handler crashed with error can't find templatefile in the path:index.html
2016/02/20 08:26:53 [router.go:860][C] /usr/src/go/src/runtime/asm_amd64.s:401
2016/02/20 08:26:53 [router.go:860][C] /usr/src/go/src/runtime/panic.go:387
2016/02/20 08:26:53 [router.go:860][C] /go/src/github.com/astaxie/beego/controller.go:262
2016/02/20 08:26:53 [router.go:860][C] /go/src/github.com/astaxie/beego/controller.go:183
2016/02/20 08:26:53 [router.go:860][C] /go/src/github.com/tobegit3hub/seagull/controllers/default.go:15
2016/02/20 08:26:53 [router.go:860][C] /go/src/github.com/astaxie/beego/router.go:760
2016/02/20 08:26:53 [router.go:860][C] /usr/src/go/src/net/http/server.go:1703
2016/02/20 08:26:53 [router.go:860][C] /usr/src/go/src/net/http/server.go:1204
2016/02/20 08:26:53 [router.go:860][C] /usr/src/go/src/runtime/asm_amd64.s:2232

any way we can fix this ?
Thank u

**Comment by rrstpit** [comment]
the same to me

**Comment by tobegit3hub** [comment]
It may be the problem after upgrading beego to 1.6.0 recently. It's really possible to fix and I'm going to update the docker image soon.

**Comment by tobegit3hub** [comment]
It may be duplicated with https://github.com/tobegit3hub/seagull/issues/66

**Comment by tobegit3hub** [comment]
I think it's fixed by https://github.com/tobegit3hub/seagull/commit/0c460878f7cb7d238915bbaab55ecd695cebebe3 . Please let me know if there's any other problem.
