### ISSUE TITLE
Handler crashed with error can't find templatefile in the path:index.html 

### ISSUE THREAD

**Issue by myml** [tobegit3hub/seagull#66]
docker logs

2016/03/05 06:32:35 [router.go:853][C] the request url is  / 
2016/03/05 06:32:35 [router.go:854][C] Handler crashed with error can't find templatefile in the path:index.html 
2016/03/05 06:32:35 [router.go:860][C] /usr/src/go/src/runtime/asm_amd64.s:401 
2016/03/05 06:32:35 [router.go:860][C] /usr/src/go/src/runtime/panic.go:387 
2016/03/05 06:32:35 [router.go:860][C] /go/src/github.com/astaxie/beego/controller.go:262 
2016/03/05 06:32:35 [router.go:860][C] /go/src/github.com/astaxie/beego/controller.go:183 
2016/03/05 06:32:35 [router.go:860][C] /go/src/github.com/tobegit3hub/seagull/controllers/default.go:15 
2016/03/05 06:32:35 [router.go:860][C] /go/src/github.com/astaxie/beego/router.go:760 
2016/03/05 06:32:35 [router.go:860][C] /usr/src/go/src/net/http/server.go:1703 
2016/03/05 06:32:35 [router.go:860][C] /usr/src/go/src/net/http/server.go:1204 
2016/03/05 06:32:35 [router.go:860][C] /usr/src/go/src/runtime/asm_amd64.s:2232

**Comment by tobegit3hub** [comment]
It may be the problem when I upgrade to the newest beego which requires golang 1.6. It is fixed by https://github.com/tobegit3hub/seagull/commit/0c460878f7cb7d238915bbaab55ecd695cebebe3 and please try after `docker pull tobegit3hub/seagull`.

Thanks for your report @myml :smiley:

**Comment by tobegit3hub** [comment]
I think it's fixed now. Please let me know if there's any other problem :smiley:
