### ISSUE TITLE
能够成功运行容器，访问10086端口，一片空白！

### ISSUE THREAD

**Issue by starjason** [tobegit3hub/seagull#67]
容器能够成功创建，但是访问10086端口，一片空白！
切换其他端口如8080等，也是一片空白。
查看日志 2016/03/26 05:08:26 [asm_amd64.s:2232][I] http server Running on :10086

**Comment by tobegit3hub** [comment]
应该是beego升级后要求使用golang 1.6，通过升级基础镜像可以解决这个问题。

Fix by https://github.com/tobegit3hub/seagull/commit/0c460878f7cb7d238915bbaab55ecd695cebebe3

**Comment by tobegit3hub** [comment]
验证通过，感谢您的支持，麻烦重新更新Seagull镜像 `docker pull tobegit3hub/seagull` 。
