### ISSUE TITLE
无法删除镜像

### ISSUE THREAD

**Issue by hutuxiaohai123** [tobegit3hub/seagull#74]
最新版本的seagull无法删除镜像

Go版本	go1.6.3
版本	1.12.3
Git提交版本	6b644ec
API版本	1.24

**Comment by tobegit3hub** [comment]
Thanks for reporting.

I think docker daemon has changed the api and add the prefix of "sha256:" for image id.

I may test and fix it soon.

**Comment by tobegit3hub** [comment]
I have fixed and test in my environment.

You can run `docker pull tobegit3hub/seagull` to upgrade the image which should work like a charm. Thanks again for reporting this.
