### ISSUE TITLE
Pack static and views folder into the binary

### ISSUE THREAD

**Issue by chneau** [tobegit3hub/seagull#77]
Idea: Using something like [static](https://github.com/rakyll/statik) to pack all html/css/js into the binary.

I believe it could potentially ease the use of the binary itself.

_Pros:_
It could greatly simplify deployment method.
```bash
go get -u github.com/tobegit3hub/seagull
```
And that's it. You can type in seagull and it's up and running. Don't need to be on `$GOPATH/src/github.com/tobegit3hub/seagull` .

_Cons:_
Either: clients need to install statik first and you can add `//go:generate statik -src=./public` to the top of the main file (here as an example).  
 
Or the git contains the generated statik file (which is basically a go file with a variable containing a "zip" and registering itself to statik library, but it's not really a code file, more like a binary file which is not very git friendly).

**Comment by tobegit3hub** [comment]
I'm not sure if it's good for relying `static` tool to package the binary since we have docker image to run `seagull` easily.
